name: Bug Report
description: Create a bug report to help us improve Effortless
labels: [ "type: bug" ]
body:
  -   type: textarea
      attributes:
        label: Describe the Bug
        description: A clear and concise description of what the bug is
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Reproduction Steps
        description: Tell us about the steps to reproduce the bug.
        value: |
          1.
          2.
          3.
          ...
      validations:
        required: false
  -   type: textarea
      attributes:
        label: Crash Report or Log
        description: If applicable, please paste the crash report or log that was created when this issue occured. You can find them in your Minecraft profile folder under ``crash-reports`` and/or under ``logs/latest.log``.
      validations:
        required: false
  -   type: textarea
      attributes:
        label: Screenshots and Videos
        description: If applicable, add screenshots or videos to help explain your problem.
      validations:
        required: false
  -   type: input
      attributes:
        label: Mod Version
        description: The version of the mod you were using when the bug occured
        placeholder: e.g. 1.8.0
        value: 1.8.0
      validations:
        required: true
  -   type: dropdown
      attributes:
        label: Minecraft Version
        description: The version of Minecraft you were using when the bug occured
        options:
          - "1.20.1"
          - "1.20.2"
          - "1.20.4"
          - "older (please state in text)"
      validations:
        required: false
  -   type: input
      attributes:
        label: Fabric Version
        description: The version of Fabric you were using when the bug occured
        placeholder: e.g. 0.15.1
      validations:
        required: false
  -   type: textarea
      attributes:
        label: Other Mods
        description: Please list any other mods that were running when the crash happened.
      validations:
        required: false
  -   type: input
      attributes:
        label: Operating System
        description: The operating system you were using when the bug occured
        placeholder: Windows 11
      validations:
        required: false
  -   type: markdown
      attributes:
        value: "Thank you for taking the time to make this bug report and help improve Effortless!"
